### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by mike1pol** [livetorrent/desktop#1]
Create project logo

**Comment by al-nkow** [comment]
![live_torrent_logo](https://cloud.githubusercontent.com/assets/5765680/11299105/093c9f46-8f95-11e5-9400-c03ac2b6484f.png)

**Comment by mike1pol** [comment]
@al-nkow can you upload as svg image (2048x2048)

**Comment by al-nkow** [comment]
[live_torrent_logo.svg.zip](https://github.com/livetorrent/desktop/files/51335/live_torrent_logo.svg.zip)
